version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ep-divine-waterfall-a52f8j9v.us-east-2.aws.neon.tech/teste-cliente
      - POSTGRES_USER=teste-cliente_owner
      - POSTGRES_PASSWORD=a0seAn4cITrw

spring-app:
  image: teste-cliente-login:latest
  ports: 
    - "8080:8080"
  environment:
    SPRING_DATASOURCE_URL:jdbc:postgresql://ep-divine-waterfall-a52f8j9v.us-east-2.aws.neon.tech/teste-cliente
  depends_on:
    - postgres-db